### PR TITLE
moved main.js to js folder

### PR DESCRIPTION
**Pull request by Aju100**
I just moved main.js file to JS folder to make it more structure of static web project.

### CODE REVIEW

**Comment by Aju100** [comment]
@prbshguragain please review the code .

**Comment by prbshguragain** [comment]
Currently, I'm dealing with many issues which require more attention than these "moving js file" these may be done later but anyway thanks for your suggestion 👍

**Comment by Aju100** [comment]
@prbshguragain  what kind of issues u are dealing. Hope I can help you too.

**Comment by Aju100** [comment]
@prbshguragain  I have added opensource license too.

**Comment by prbshguragain** [comment]
It was fetching the data of radio button into firebase realtime database using JS but it is fixed now.

**Review by prbshguragain — APPROVED** [review]

**Comment by Aju100** [comment]
awesome.

**Pull request closed without merging**
